# ruff.toml

# --- Configuración general ---
line-length = 88
target-version = "py313"

# --- Exclusiones globales ---
exclude = [
    "__pycache__",
    ".git",
    ".venv",
    "build",
    "dist",
    "tests",
]

# --- Linter (errores, warnings, estilos) ---
[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # import sorting (isort)
    "B",  # flake8-bugbear
]
ignore = [
    "W291",  # trailing whitespace
    "E501",  # line too long, handled by black
    "B008",  # function calls in argument defaults
    "S101",  # use of assert (pytest allows it)
    "S110",  # raising exception in __init__
    "S112",  # assert detected again
]

[lint.per-file-ignores]
"tests/*" = ["S101", "S106", "S108"]

# --- Formateador (sustituye a Black) ---
[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

# --- Import sorting (equivalente a isort) ---
[lint.isort]
known-first-party = ["src"]   # como tu src_paths
